### ISSUE TITLE
'+ New post' blog button is partially hidden

### ISSUE THREAD

**Issue by mathias-erik** [Edicy/design-stockholm#1]

**Comment by kaspar-naaber** [comment]
Couldn't reproduce. Are you sure this issue is under the correct version of Stockholm template?
(https://github.com/Edicy/design-stockholmnorth) and (https://github.com/Edicy/design-stockholm-old)

Maybe the template wasn't updated in Voog while you were testing? Reopen the issue if it still occurs

**Comment by tanelj** [comment]
There is surrounding p-tags  `<p>{% addbutton class="add-article" %}</p>` that brakes html (looks different in IE and FF):

![stockholm-blog-add-button](https://cloud.githubusercontent.com/assets/378755/5838049/12260788-a18d-11e4-9d7f-26a3b7c64914.png)
